// src/data.js

import {
  Home,
  Users,
  Package,
  ShoppingCart,
  BarChart3,
  Settings,
} from "lucide-react";

export const menuItems = [
  { id: "dashboard", label: "Dashboard", icon: Home },
  { id: "bookings", label: "Đặt Tour", icon: ShoppingCart },
  { id: "tours", label: "Quản lý Tour", icon: Package },
  { id: "customers", label: "Khách hàng", icon: Users },
  // { id: "analytics", label: "Thống kê", icon: BarChart3 },
  { id: "settings", label: "Cài đặt", icon: Settings },
];

export const salesData = [
  { name: "T10", sales: 8, revenue: 2500 },
  { name: "T11", sales: 0, revenue: 0 },
  { name: "T12", sales: 0, revenue: 0 },
  { name: "T1", sales: 0, revenue: 0 },
  { name: "T2", sales: 0, revenue: 0 },
  { name: "T3", sales: 0, revenue: 0 },
  { name: "T4", sales: 0, revenue: 0 },
];

export const pieData = [
  { name: "Du thuyền cao cấp", value: 400, color: "#14B8A6" },
  { name: "Du thuyền trung cấp", value: 300, color: "#0891B2" },
  { name: "Du thuyền bình dân", value: 300, color: "#0F766E" },
  { name: "Tour khác", value: 200, color: "#84CC16" },
];

export const recentBookings = [
  {
    id: 1,
    customer: "Nguyễn Văn A",
    tour: "Heritage Bình Chuẩn Cát Bà",
    date: "2025-01-20",
    status: "confirmed",
    amount: "4,150,000đ",
  },
  {
    id: 2,
    customer: "Trần Thị B",
    tour: "Ambassador Hạ Long",
    date: "2025-01-22",
    status: "pending",
    amount: "3,850,000đ",
  },
  {
    id: 3,
    customer: "Lê Văn C",
    tour: "Grand Pioneers",
    date: "2025-01-25",
    status: "confirmed",
    amount: "5,150,000đ",
  },
  {
    id: 4,
    customer: "Phạm Thị D",
    tour: "Capella",
    date: "2025-01-28",
    status: "cancelled",
    amount: "2,950,000đ",
  },
];

export const allBookingsData = [
  {
    id: 1,
    customer: "Nguyễn Văn A",
    tour: "Heritage Bình Chuẩn Cát Bà",
    date: "2025-01-20",
    status: "confirmed",
    amount: "4,150,000đ",
  },
  {
    id: 2,
    customer: "Trần Thị B",
    tour: "Ambassador Hạ Long",
    date: "2025-01-22",
    status: "pending",
    amount: "3,850,000đ",
  },
  {
    id: 3,
    customer: "Lê Văn C",
    tour: "Grand Pioneers",
    date: "2025-01-25",
    status: "confirmed",
    amount: "5,150,000đ",
  },
  {
    id: 4,
    customer: "Phạm Thị D",
    tour: "Capella",
    date: "2025-01-28",
    status: "cancelled",
    amount: "2,950,000đ",
  },
  {
    id: 5,
    customer: "Hoàng Văn E",
    tour: "Stellar of the Seas",
    date: "2025-02-01",
    status: "confirmed",
    amount: "6,200,000đ",
  },
  {
    id: 6,
    customer: "Vũ Thị F",
    tour: "Paradise Grand",
    date: "2025-02-05",
    status: "pending",
    amount: "4,500,000đ",
  },
  {
    id: 7,
    customer: "Đặng Văn G",
    tour: "Scarlet Pearl",
    date: "2025-02-10",
    status: "confirmed",
    amount: "7,000,000đ",
  },
  {
    id: 8,
    customer: "Bùi Thị H",
    tour: "La Casta Regal",
    date: "2025-02-12",
    status: "cancelled",
    amount: "3,100,000đ",
  },
  {
    id: 9,
    customer: "Hồ Văn I",
    tour: "Ambassador Hạ Long",
    date: "2025-02-15",
    status: "confirmed",
    amount: "3,850,000đ",
  },
  {
    id: 10,
    customer: "Ngô Thị K",
    tour: "Heritage Bình Chuẩn Cát Bà",
    date: "2025-02-20",
    status: "pending",
    amount: "4,150,000đ",
  },
  {
    id: 11,
    customer: "Dương Văn M",
    tour: "Catherine Cruise",
    date: "2025-03-01",
    status: "confirmed",
    amount: "5,500,000đ",
  },
  {
    id: 12,
    customer: "Lý Thị N",
    tour: "Stellar of the Seas",
    date: "2025-03-05",
    status: "pending",
    amount: "6,200,000đ",
  },
  {
    id: 13,
    customer: "Mai Văn P",
    tour: "Paradise Grand",
    date: "2025-03-10",
    status: "confirmed",
    amount: "4,500,000đ",
  },
  {
    id: 14,
    customer: "Trịnh Thị Q",
    tour: "Ambassador Hạ Long",
    date: "2025-03-12",
    status: "cancelled",
    amount: "3,850,000đ",
  },
  {
    id: 15,
    customer: "Vương Văn R",
    tour: "Capella",
    date: "2025-03-15",
    status: "confirmed",
    amount: "2,950,000đ",
  },
];

export const allToursData = [
  {
    id: "T001",
    name: "Heritage Bình Chuẩn Cát Bà",
    destination: "Vịnh Lan Hạ",
    duration: "2 ngày 1 đêm",
    price: "4,150,000đ",
    status: "active",
  },
  {
    id: "T002",
    name: "Ambassador Hạ Long",
    destination: "Vịnh Hạ Long",
    duration: "2 ngày 1 đêm",
    price: "3,850,000đ",
    status: "active",
  },
  {
    id: "T003",
    name: "Grand Pioneers",
    destination: "Vịnh Lan Hạ",
    duration: "3 ngày 2 đêm",
    price: "5,150,000đ",
    status: "active",
  },
  {
    id: "T004",
    name: "Capella",
    destination: "Vịnh Hạ Long",
    duration: "2 ngày 1 đêm",
    price: "2,950,000đ",
    status: "inactive",
  },
  {
    id: "T005",
    name: "Stellar of the Seas",
    destination: "Vịnh Hạ Long",
    duration: "3 ngày 2 đêm",
    price: "6,200,000đ",
    status: "active",
  },
  {
    id: "T006",
    name: "Paradise Grand",
    destination: "Vịnh Lan Hạ",
    duration: "2 ngày 1 đêm",
    price: "4,500,000đ",
    status: "active",
  },
  {
    id: "T007",
    name: "Scarlet Pearl",
    destination: "Vịnh Hạ Long",
    duration: "3 ngày 2 đêm",
    price: "7,000,000đ",
    status: "active",
  },
  {
    id: "T008",
    name: "La Casta Regal",
    destination: "Vịnh Lan Hạ",
    duration: "2 ngày 1 đêm",
    price: "3,100,000đ",
    status: "inactive",
  },
  {
    id: "T009",
    name: "Catherine Cruise",
    destination: "Vịnh Hạ Long",
    duration: "2 ngày 1 đêm",
    price: "5,500,000đ",
    status: "active",
  },
  {
    id: "T010",
    name: "Rita Cruise",
    destination: "Vịnh Lan Hạ",
    duration: "3 ngày 2 đêm",
    price: "6,800,000đ",
    status: "active",
  },
  {
    id: "T011",
    name: "Peony Cruises",
    destination: "Vịnh Hạ Long",
    duration: "2 ngày 1 đêm",
    price: "3,200,000đ",
    status: "active",
  },
  {
    id: "T012",
    name: "Dora Cruise",
    destination: "Vịnh Lan Hạ",
    duration: "2 ngày 1 đêm",
    price: "4,000,000đ",
    status: "inactive",
  },
];

export const allCustomersData = [
  {
    id: "C001",
    name: "Nguyễn Văn A",
    email: "nguyenvana@email.com",
    phone: "0901234567",
    joinDate: "2024-01-15",
    status: "active",
  },
  {
    id: "C002",
    name: "Trần Thị B",
    email: "tranthib@email.com",
    phone: "0912345678",
    joinDate: "2024-02-20",
    status: "active",
  },
  {
    id: "C003",
    name: "Lê Văn C",
    email: "levanc@email.com",
    phone: "0987654321",
    joinDate: "2024-03-10",
    status: "banned",
  },
  {
    id: "C004",
    name: "Phạm Thị D",
    email: "phamthid@email.com",
    phone: "0978123456",
    joinDate: "2024-05-01",
    status: "active",
  },
  {
    id: "C005",
    name: "Hoàng Văn E",
    email: "hoangvane@email.com",
    phone: "0934567890",
    joinDate: "2024-06-18",
    status: "active",
  },
  {
    id: "C006",
    name: "Vũ Thị F",
    email: "vuthif@email.com",
    phone: "0945678901",
    joinDate: "2024-08-22",
    status: "active",
  },
  {
    id: "C007",
    name: "Đặng Văn G",
    email: "dangvang@email.com",
    phone: "0902345678",
    joinDate: "2024-09-01",
    status: "active",
  },
  {
    id: "C008",
    name: "Bùi Thị H",
    email: "buithih@email.com",
    phone: "0913456789",
    joinDate: "2024-10-11",
    status: "active",
  },
  {
    id: "C009",
    name: "Hồ Văn I",
    email: "hovani@email.com",
    phone: "0988765432",
    joinDate: "2024-11-05",
    status: "banned",
  },
  {
    id: "C010",
    name: "Ngô Thị K",
    email: "ngothik@email.com",
    phone: "0977123456",
    joinDate: "2024-12-15",
    status: "active",
  },
  {
    id: "C011",
    name: "Dương Văn M",
    email: "duongvanm@email.com",
    phone: "0933567890",
    joinDate: "2025-01-20",
    status: "active",
  },
];

export const revenueProfitData = [
  { name: "T1", revenue: 4000, profit: 2400 },
  { name: "T2", revenue: 3000, profit: 1398 },
  { name: "T3", revenue: 2000, profit: 1800 },
  { name: "T4", revenue: 2780, profit: 1908 },
  { name: "T5", revenue: 1890, profit: 800 },
  { name: "T6", revenue: 2390, profit: 1800 },
  { name: "T7", revenue: 3490, profit: 2300 },
  { name: "T8", revenue: 4200, profit: 2500 },
];

export const topToursByRevenue = [
  { name: "Heritage Bình Chuẩn", revenue: "1.2 tỷ", bookings: 290 },
  { name: "Ambassador Hạ Long", revenue: "980 triệu", bookings: 250 },
  { name: "Stellar of the Seas", revenue: "850 triệu", bookings: 140 },
  { name: "Scarlet Pearl", revenue: "700 triệu", bookings: 100 },
  { name: "Paradise Grand", revenue: "650 triệu", bookings: 150 },
];
