// src/styles.js

export const styles = {
  container: {
    display: "flex",
    height: "100vh",
    width: "100vw",
    backgroundColor: "#f3f4f6",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    margin: 0,
    padding: 0,
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  sidebar: {
    backgroundColor: "white",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    transition: "all 0.3s ease",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: "16px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  logo: {
    width: "32px",
    height: "32px",
    backgroundColor: "#14B8A6",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: { fontSize: "20px", fontWeight: "bold", color: "#1f2937" },
  nav: { marginTop: "32px" },
  navItem: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    padding: "12px 16px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    transition: "all 0.2s ease",
    color: "#6b7280",
    textAlign: "left",
  },
  navItemActive: {
    backgroundColor: "#f0fdfa",
    color: "#0f766e",
    borderRight: "2px solid #14B8A6",
  },
  navItemHover: { backgroundColor: "#f0fdfa", color: "#0f766e" },
  navItemText: { marginLeft: "12px", whiteSpace: "nowrap" },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    backgroundColor: "white",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    padding: "16px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "16px" },
  headerTitle: {
    fontSize: "24px",
    fontWeight: "600",
    color: "#1f2937",
    margin: 0,
  },
  headerRight: { display: "flex", alignItems: "center", gap: "16px" },
  searchContainer: { position: "relative" },
  searchInput: {
    paddingLeft: "40px",
    paddingRight: "16px",
    paddingTop: "8px",
    paddingBottom: "8px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    outline: "none",
    width: "200px",
    backgroundColor: "white",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
  },
  notificationBtn: {
    position: "relative",
    padding: "8px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    borderRadius: "6px",
    color: "#6b7280",
  },
  notificationBadge: {
    position: "absolute",
    top: "-4px",
    right: "-4px",
    backgroundColor: "#ef4444",
    color: "white",
    fontSize: "10px",
    borderRadius: "50%",
    width: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userProfile: { display: "flex", alignItems: "center", gap: "12px" },
  userAvatar: {
    width: "32px",
    height: "32px",
    backgroundColor: "#14B8A6",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontSize: "14px",
    fontWeight: "500",
  },
  customerAvatar: {
    width: "32px",
    height: "32px",
    backgroundColor: "#0891B2",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontSize: "14px",
    fontWeight: "500",
    marginRight: "12px",
  },
  userInfo: { display: "block" },
  userName: {
    fontWeight: "500",
    color: "#1f2937",
    fontSize: "14px",
    margin: 0,
  },
  userEmail: { color: "#6b7280", fontSize: "12px", margin: 0 },
  content: { flex: 1, overflowY: "auto", padding: "24px" },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "24px",
    marginBottom: "24px",
  },
  statCard: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
  },
  statCardContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statCardLeft: { flex: 1 },
  statCardTitle: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#6b7280",
    margin: "0 0 4px 0",
  },
  statCardValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#1f2937",
    margin: "0 0 8px 0",
  },
  statCardChange: { display: "flex", alignItems: "center", gap: "4px" },
  statCardTrend: { fontSize: "14px" },
  statCardIcon: {
    backgroundColor: "#f0fdfa",
    padding: "12px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  chartsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    marginBottom: "24px",
  },
  chartCard: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
  },
  chartTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "16px",
  },
  table: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    overflow: "hidden",
  },
  tableHeader: {
    padding: "24px",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  tableTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
    margin: 0,
  },
  tableActions: {
    color: "#14B8A6",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "500",
  },
  tableContent: { overflowX: "auto" },
  tableEl: { width: "100%", borderCollapse: "collapse", tableLayout: "fixed" },
  tableHead: { backgroundColor: "#f9fafb" },
  tableHeadCell: {
    padding: "12px 24px",
    textAlign: "left",
    fontSize: "12px",
    fontWeight: "500",
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  tableCell: {
    padding: "16px 24px",
    fontSize: "14px",
    verticalAlign: "middle",
  },
  tableCellEllipsis: {
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  statusBadge: {
    display: "inline-flex",
    padding: "2px 8px",
    fontSize: "12px",
    fontWeight: "600",
    borderRadius: "12px",
  },
  actionButtons: { display: "flex", gap: "8px" },
  actionBtn: {
    padding: "4px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    borderRadius: "4px",
  },
  primaryButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#14B8A6",
    color: "white",
    border: "none",
    padding: "10px 16px",
    borderRadius: "6px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  secondaryButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#f3f4f6",
    color: "#374151",
    border: "1px solid #d1d5db",
    padding: "10px 16px",
    borderRadius: "6px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  paginationContainer: {
    padding: "16px 24px",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    borderTop: "1px solid #e5e7eb",
    color: "#6b7280",
    fontSize: "14px",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginLeft: "24px",
  },
  paginationButton: {
    padding: "8px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    color: "#6b7280",
    transition: "background-color 0.2s",
  },
  paginationButtonDisabled: { cursor: "not-allowed", opacity: 0.5 },
  formGroup: { marginBottom: "20px" },
  formLabel: {
    display: "block",
    fontWeight: "500",
    color: "#374151",
    marginBottom: "8px",
    fontSize: "14px",
  },
  formInput: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    outline: "none",
    boxSizing: "border-box",
    backgroundColor: "white",
  },
  formTextarea: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    backgroundColor: "white",
  },
  formSelect: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    outline: "none",
    boxSizing: "border-box",
    backgroundColor: "white",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(17, 24, 39, 0.3)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContainer: {
    backgroundColor: "white",
    borderRadius: "8px",
    width: "90%",
    maxWidth: "500px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
  modalHeader: {
    padding: "16px 24px",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: { margin: 0, fontSize: "18px", fontWeight: "600" },
  modalCloseButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px",
  },
  modalBody: { padding: "24px" },
  modalFooter: {
    padding: "16px 24px",
    borderTop: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
  },
  settingsCard: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    marginBottom: "24px",
  },
  settingsHeader: { padding: "16px 24px", borderBottom: "1px solid #e5e7eb" },
  settingsTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
    margin: 0,
  },
  settingsContent: { padding: "24px" },
  settingsTabsContainer: {
    borderBottom: "1px solid #e5e7eb",
    marginBottom: "24px",
    display: "flex",
  },
  settingsTab: {
    padding: "12px 20px",
    cursor: "pointer",
    border: "none",
    backgroundColor: "transparent",
    color: "#6b7280",
    fontWeight: "500",
    borderBottom: "2px solid transparent",
  },
  settingsTabActive: { color: "#14B8A6", borderBottom: "2px solid #14B8A6" },
  settingsFooter: {
    paddingTop: "20px",
    marginTop: "20px",
    borderTop: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "flex-end",
  },
};
